---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

images:
  - name: docker.pkg.github.com/nicolast/contained-ganesha/rpcbind
    newName: docker.io/nicolast/contained-ganesha-rpcbind
    newTag: latest
  - name: docker.pkg.github.com/nicolast/contained-ganesha/rpc.statd
    newName: docker.io/nicolast/contained-ganesha-rpc.statd
    newTag: latest
  - name: docker.pkg.github.com/nicolast/contained-ganesha/dbus-daemon
    newName: docker.io/nicolast/contained-ganesha-dbus-daemon
    newTag: latest
  - name: docker.pkg.github.com/nicolast/contained-ganesha/nfs-ganesha
    newName: docker.io/nicolast/contained-ganesha-nfs-ganesha
    newTag: latest
  - name: docker.pkg.github.com/nicolast/contained-ganesha/ganesha-config-reload
    newName: docker.io/nicolast/contained-ganesha-ganesha-config-reload
    newTag: latest
