name: CI/CD

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  check-ganesha-config-reload:
    name: Check ganesha-config-reload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Install Go
        uses: actions/setup-go@v6.0.0
        with:
          cache-dependency-path: |
            ganesha-config-reload/go.sum
      - name: Test
        run: |
          go test -v ./...
        working-directory: ./ganesha-config-reload

  build:
    name: Build container images
    needs:
      - check-ganesha-config-reload
    strategy:
      matrix:
        docker: [docker, podman]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Fetch tags
        run: |
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          git fetch --prune --unshallow origin HEAD
      - name: Login to container image registry
        run: |
          echo ${GITHUB_TOKEN} | ${DOCKER} login -u ${GITHUB_ACTOR} --password-stdin docker.pkg.github.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER: ${{ matrix.docker }}
      - name: Pull container images from registry
        run: |
          source .env
          ${DOCKER} pull ${RPCBIND_IMAGE}:${RPCBIND_TAG} || true
          ${DOCKER} pull ${RPC_STATD_IMAGE}:${RPC_STATD_TAG} || true
          ${DOCKER} pull ${DBUS_DAEMON_IMAGE}:${DBUS_DAEMON_TAG} || true
          ${DOCKER} pull ${NFS_GANESHA_IMAGE}:${NFS_GANESHA_TAG} || true
          ${DOCKER} pull ${GANESHA_CONFIG_RELOAD_IMAGE}:${GANESHA_CONFIG_RELOAD_TAG} || true
          ${DOCKER} pull ${CONTAINED_GANESHA_TEST_IMAGE}:${CONTAINED_GANESHA_TEST_TAG} || true
        env:
          DOCKER: ${{ matrix.docker }}
      - name: Build container images
        run: |
          make containers container-contained-ganesha-test DOCKER=${DOCKER}
        env:
          DOCKER: ${{ matrix.docker }}
      - name: Export container images
        run: |
          mkdir container-images
          source .env

          if [ ${DOCKER} = "podman" ]; then
              EXTRA_ARGS="--multi-image-archive"
          fi

          ${DOCKER} save \
              ${EXTRA_ARGS:-} \
              ${LOCAL_RPCBIND_IMAGE}:${LOCAL_RPCBIND_TAG} \
              ${LOCAL_RPC_STATD_IMAGE}:${LOCAL_RPC_STATD_TAG} \
              ${LOCAL_DBUS_DAEMON_IMAGE}:${LOCAL_DBUS_DAEMON_TAG} \
              ${LOCAL_NFS_GANESHA_IMAGE}:${LOCAL_NFS_GANESHA_TAG} \
              ${LOCAL_GANESHA_CONFIG_RELOAD_IMAGE}:${LOCAL_GANESHA_CONFIG_RELOAD_TAG} \
              ${LOCAL_CONTAINED_GANESHA_TEST_IMAGE}:${LOCAL_CONTAINED_GANESHA_TEST_TAG} \
              | gzip > container-images/build.tar.gz
        env:
          DOCKER: ${{ matrix.docker }}
      - name: Archive artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: container-images-${{ matrix.docker }}
          path: container-images
          if-no-files-found: error

  test-docker-compose:
    name: Test docker-compose
    needs:
      - build
    strategy:
      matrix:
        docker: [docker, podman]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Retrieve artifacts
        uses: actions/download-artifact@v6.0.0
        with:
          name: container-images-${{ matrix.docker }}
          path: container-images/
      - name: Import container images
        run: |
          cat container-images/build.tar.gz | gzip -d | docker load
      - name: Re-tag container images
        if: ${{ matrix.docker == 'podman' }}
        run: |
          source .env

          docker tag localhost/${LOCAL_RPCBIND_IMAGE}:${LOCAL_RPCBIND_TAG} ${LOCAL_RPCBIND_IMAGE}:${LOCAL_RPCBIND_TAG}
          docker tag localhost/${LOCAL_RPC_STATD_IMAGE}:${LOCAL_RPC_STATD_TAG} ${LOCAL_RPC_STATD_IMAGE}:${LOCAL_RPC_STATD_TAG}
          docker tag localhost/${LOCAL_DBUS_DAEMON_IMAGE}:${LOCAL_DBUS_DAEMON_TAG} ${LOCAL_DBUS_DAEMON_IMAGE}:${LOCAL_DBUS_DAEMON_TAG}
          docker tag localhost/${LOCAL_NFS_GANESHA_IMAGE}:${LOCAL_NFS_GANESHA_TAG} ${LOCAL_NFS_GANESHA_IMAGE}:${LOCAL_NFS_GANESHA_TAG}
          docker tag localhost/${LOCAL_GANESHA_CONFIG_RELOAD_IMAGE}:${LOCAL_GANESHA_CONFIG_RELOAD_TAG} ${LOCAL_GANESHA_CONFIG_RELOAD_IMAGE}:${LOCAL_GANESHA_CONFIG_RELOAD_TAG}
          docker tag localhost/${LOCAL_CONTAINED_GANESHA_TEST_IMAGE}:${LOCAL_CONTAINED_GANESHA_TEST_TAG} ${LOCAL_CONTAINED_GANESHA_TEST_IMAGE}:${LOCAL_CONTAINED_GANESHA_TEST_TAG}
      - name: Test
        run: |
          make -C deploy/docker-compose check-nobuild
      - name: Cleanup
        run: |
          make -C deploy/docker-compose down

  test-kubernetes:
    name: Test Kubernetes (using Kind)
    needs:
      - build
    strategy:
      matrix:
        docker: [docker, podman]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Retrieve artifacts
        uses: actions/download-artifact@v6.0.0
        with:
          name: container-images-${{ matrix.docker }}
          path: container-images/
      - name: Build manifests
        run: |
          make -C deploy/kubernetes manifests
      - name: Import container images
        run: |
          cat container-images/build.tar.gz | gzip -d | docker load
      - name: Re-tag container images
        if: ${{ matrix.docker == 'podman' }}
        run: |
          source .env

          docker tag localhost/${LOCAL_RPCBIND_IMAGE}:${LOCAL_RPCBIND_TAG} ${LOCAL_RPCBIND_IMAGE}:${LOCAL_RPCBIND_TAG}
          docker tag localhost/${LOCAL_RPC_STATD_IMAGE}:${LOCAL_RPC_STATD_TAG} ${LOCAL_RPC_STATD_IMAGE}:${LOCAL_RPC_STATD_TAG}
          docker tag localhost/${LOCAL_DBUS_DAEMON_IMAGE}:${LOCAL_DBUS_DAEMON_TAG} ${LOCAL_DBUS_DAEMON_IMAGE}:${LOCAL_DBUS_DAEMON_TAG}
          docker tag localhost/${LOCAL_NFS_GANESHA_IMAGE}:${LOCAL_NFS_GANESHA_TAG} ${LOCAL_NFS_GANESHA_IMAGE}:${LOCAL_NFS_GANESHA_TAG}
          docker tag localhost/${LOCAL_GANESHA_CONFIG_RELOAD_IMAGE}:${LOCAL_GANESHA_CONFIG_RELOAD_TAG} ${LOCAL_GANESHA_CONFIG_RELOAD_IMAGE}:${LOCAL_GANESHA_CONFIG_RELOAD_TAG}
          docker tag localhost/${LOCAL_CONTAINED_GANESHA_TEST_IMAGE}:${LOCAL_CONTAINED_GANESHA_TEST_TAG} ${LOCAL_CONTAINED_GANESHA_TEST_IMAGE}:${LOCAL_CONTAINED_GANESHA_TEST_TAG}
      - name: Start Kind cluster
        uses: helm/kind-action@v1.12.0
        with:
          cluster_name: kind
      - name: Import Docker images into Kind cluster
        run: |
          make -C deploy/kubernetes kind-load-docker-images-nobuild kind-load-cgt-image-nobuild
      - name: Deploy
        run: |
          make -C deploy/kubernetes kubectl-local-apply
      - name: Test
        run: |
          make -C deploy/kubernetes check
      - name: Cleanup
        run: |
          make -C deploy/kubernetes kubectl-local-delete

  test-podman:
    name: Test podman
    needs:
      - build
    strategy:
      matrix:
        docker: [docker, podman]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Retrieve artifacts
        uses: actions/download-artifact@v6.0.0
        with:
          name: container-images-${{ matrix.docker }}
          path: container-images/
      - name: Import container images
        run: |
          cat container-images/build.tar.gz | gzip -d | podman load
      - name: Test
        run: |
          make -C deploy/podman check-nobuild
      - name: Cleanup
        run: |
          make -C deploy/podman down

  tests-success:
    runs-on: ubuntu-latest
    if: ${{ always () }}
    needs:
      - test-docker-compose
      - test-kubernetes
      - test-podman
    steps:
      - name: Ensure tests succeeded
        if: "${{ (needs.test-docker-compose.result != 'success') || (needs.test-kubernetes.result != 'success') || (needs.test-podman.result != 'success') }}"
        run: |
          exit 1

  publish-github:
    name: Publish container images to GitHub Packages
    if: github.ref == 'refs/heads/master'
    needs:
      - build
      - tests-success
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Retrieve artifacts
        uses: actions/download-artifact@v6.0.0
        with:
          name: container-images-docker
          path: container-images/
      - name: Import container images
        run: |
          cat container-images/build.tar.gz | gzip -d | docker load
      - name: Tag container images
        run: |
          source .env
          docker tag ${LOCAL_RPCBIND_IMAGE}:${LOCAL_RPCBIND_TAG} ${RPCBIND_IMAGE}:${RPCBIND_TAG}
          docker tag ${LOCAL_RPC_STATD_IMAGE}:${LOCAL_RPC_STATD_TAG} ${RPC_STATD_IMAGE}:${RPC_STATD_TAG}
          docker tag ${LOCAL_DBUS_DAEMON_IMAGE}:${LOCAL_DBUS_DAEMON_TAG} ${DBUS_DAEMON_IMAGE}:${DBUS_DAEMON_TAG}
          docker tag ${LOCAL_NFS_GANESHA_IMAGE}:${LOCAL_NFS_GANESHA_TAG} ${NFS_GANESHA_IMAGE}:${NFS_GANESHA_TAG}
          docker tag ${LOCAL_GANESHA_CONFIG_RELOAD_IMAGE}:${LOCAL_GANESHA_CONFIG_RELOAD_TAG} ${GANESHA_CONFIG_RELOAD_IMAGE}:${GANESHA_CONFIG_RELOAD_TAG}
          docker tag ${LOCAL_CONTAINED_GANESHA_TEST_IMAGE}:${LOCAL_CONTAINED_GANESHA_TEST_TAG} ${CONTAINED_GANESHA_TEST_IMAGE}:${CONTAINED_GANESHA_TEST_TAG}
      - name: Login to container image registry
        run: |
          echo ${GITHUB_TOKEN} | docker login -u ${GITHUB_ACTOR} --password-stdin docker.pkg.github.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push container images
        run: |
          source .env
          docker push ${RPCBIND_IMAGE}:${RPCBIND_TAG}
          docker push ${RPC_STATD_IMAGE}:${RPC_STATD_TAG}
          docker push ${DBUS_DAEMON_IMAGE}:${DBUS_DAEMON_TAG}
          docker push ${NFS_GANESHA_IMAGE}:${NFS_GANESHA_TAG}
          docker push ${GANESHA_CONFIG_RELOAD_IMAGE}:${GANESHA_CONFIG_RELOAD_TAG}
          docker push ${CONTAINED_GANESHA_TEST_IMAGE}:${CONTAINED_GANESHA_TEST_TAG}

  publish-dockerhub:
    name: Publish container images to DockerHub
    if: github.ref == 'refs/heads/master'
    needs:
      - build
      - tests-success
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Retrieve artifacts
        uses: actions/download-artifact@v6.0.0
        with:
          name: container-images-docker
          path: container-images/
      - name: Import container images
        run: |
          cat container-images/build.tar.gz | gzip -d | docker load
      - name: Tag container images
        run: |
          source .env
          docker tag ${LOCAL_RPCBIND_IMAGE}:${LOCAL_RPCBIND_TAG} docker.io/nicolast/contained-ganesha-rpcbind:latest
          docker tag ${LOCAL_RPC_STATD_IMAGE}:${LOCAL_RPC_STATD_TAG} docker.io/nicolast/contained-ganesha-rpc.statd:latest
          docker tag ${LOCAL_DBUS_DAEMON_IMAGE}:${LOCAL_DBUS_DAEMON_TAG} docker.io/nicolast/contained-ganesha-dbus-daemon:latest
          docker tag ${LOCAL_NFS_GANESHA_IMAGE}:${LOCAL_NFS_GANESHA_TAG} docker.io/nicolast/contained-ganesha-nfs-ganesha:latest
          docker tag ${LOCAL_GANESHA_CONFIG_RELOAD_IMAGE}:${LOCAL_GANESHA_CONFIG_RELOAD_TAG} docker.io/nicolast/contained-ganesha-ganesha-config-reload:latest
      - name: Login to container image registry
        run: |
          echo ${DOCKERHUB_TOKEN} | docker login -u nicolast --password-stdin
        env:
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push container images
        run: |
          docker push docker.io/nicolast/contained-ganesha-rpcbind:latest
          docker push docker.io/nicolast/contained-ganesha-rpc.statd:latest
          docker push docker.io/nicolast/contained-ganesha-dbus-daemon:latest
          docker push docker.io/nicolast/contained-ganesha-nfs-ganesha:latest
          docker push docker.io/nicolast/contained-ganesha-ganesha-config-reload:latest
